// Bundle the conformance CLI into one ESM file runnable with plain `node` (or `npx`).
// The WCP reference coordinator (the oracle) is bundled in; there are no runtime deps.
import { build } from "esbuild";
import { cpSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(dirname(fileURLToPath(import.meta.url)));
await build({
  entryPoints: { "wcp-hook-conformance": join(here, "src/cli.ts") },
  outdir: join(here, "dist"),
  outExtension: { ".js": ".mjs" },
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  banner: { js: "// @weft/hook-conformance — generated by scripts/build.mjs; do not edit." },
  logLevel: "warning",
});
cpSync(join(here, "fixtures"), join(here, "dist", "fixtures"), { recursive: true });
