#!/usr/bin/env node
// Regenerate docs/standardization/reports/ — run from the repo root after building the
// adapters (each adapter's `pnpm test` builds its bundle) and this package:
//
//   node packages/conformance/scripts/weft-reports.mjs
//
// Every Weft hook translator is driven through the core fixtures in its own harness's
// native dialect, plus two extra subjects: the core stdio binding (via `bridge`) and the
// Claude Code adapter in advisory mode (to show what an over-declaration looks like).
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = process.cwd();
const cli = "packages/conformance/bin/wcp-hook-conformance.mjs";
const out = "docs/standardization/reports";
mkdirSync(out, { recursive: true });

const bundle = (pkg, name) => `packages/adapters/${pkg}/dist/${name}.mjs`;
const install = (b) => `node ${resolve(root, b)} install --url {url} --repo {repo} --agent {agent} --task {task} --title conformance`;

const subjects = [
  { file: "claude-code", subject: "Claude Code adapter (@weft/adapter-claude-code)", dialect: "claude-code", b: bundle("claude-code", "weft-claude") },
  { file: "codex", subject: "Codex adapter (@weft/adapter-codex)", dialect: "codex", b: bundle("codex", "weft-codex") },
  { file: "opencode", subject: "OpenCode adapter (@weft/adapter-opencode, plugin bridge)", dialect: "opencode", b: bundle("opencode", "weft-opencode") },
  { file: "cursor", subject: "Cursor CLI translator (@weft/adapter-cursor)", dialect: "cursor", b: bundle("cursor", "weft-cursor") },
  { file: "gemini", subject: "Gemini CLI translator (@weft/adapter-gemini)", dialect: "gemini", b: bundle("gemini", "weft-gemini") },
  { file: "core-binding", subject: "Core stdio binding (bridge → Claude Code adapter)", dialect: "core", b: bundle("claude-code", "weft-claude"), bridge: "claude-code" },
  { file: "claude-code-advise", subject: "Claude Code adapter in advisory mode (WEFT_MODE=advise)", dialect: "claude-code", b: bundle("claude-code", "weft-claude"), env: ["WEFT_MODE=advise"] },
];

const rows = [];
for (const s of subjects) {
  const hook = s.bridge ? [cli, "bridge", "--dialect", s.bridge, "--", "node", s.b, "hook"] : ["node", s.b, "hook"];
  const args = [cli, "run", "--dialect", s.dialect, "--subject", s.subject, "--setup", install(s.b), "--env", "WEFT_TOKEN=conformance-token", ...(s.env ?? []).flatMap((e) => ["--env", e]), "--json", join(out, `${s.file}.json`), "--md", join(out, `${s.file}.md`), "--", ...(s.bridge ? ["node", ...hook] : hook)];
  process.stderr.write(`\n=== ${s.subject}\n`);
  try {
    execFileSync(process.execPath, args, { stdio: ["ignore", "ignore", "inherit"] });
  } catch {
    /* non-zero = over-declaration; the report is still written */
  }
  const r = JSON.parse(readFileSync(join(out, `${s.file}.json`), "utf8"));
  const lvl = (n) => (n < 0 ? "none" : `L${n}`);
  rows.push(`| [${s.subject}](${s.file}.md) | \`${s.dialect}\` | ${r.declared.capabilities ? lvl(r.declared.capabilities.level) : "—"} | **${lvl(r.verified_level)}** | ${r.honest === null ? "n/a" : r.honest ? "yes" : "**no**"} | ${r.commit_gate} | ${r.failure_policy} | ${r.latency_ms.p50} / ${r.latency_ms.max} |`);
}

const readme = `# Conformance reports

Generated by \`node packages/conformance/scripts/weft-reports.mjs\` with
[\`wcp-hook-conformance\`](../../../packages/conformance/README.md) against the Agent Hooks Core v0
fixtures ([spec §11](../../protocol/hooks-core-v0.md#11-conformance)). Each subject is the real
hook command (the adapter's bundled \`hook\` entry), driven one process per event in its own
harness's native hook dialect, against a local WCP reference coordinator as the oracle.

| Subject | Dialect | Declared | Verified | Honest | Commit gate | Backend down | Hook ms p50 / max |
|---|---|---|---|---|---|---|---|
${rows.join("\n")}

What these reports prove, and what they do not:

- They verify the **hook command**: given the native JSON a harness documents, it answers with the
  native JSON that carries the right core decision (allow / advise / deny with an explanation), in time,
  and records what it observed. That is the portable part a standard can test.
- They do **not** prove that a given harness version actually invokes the hook or honours the answer.
  That is live verification, tracked per harness in [docs/research/hooks.md](../../research/hooks.md)
  and the M2 runs ([demo/evidence/m2-report.md](../../../demo/evidence/m2-report.md)): Claude Code and
  OpenCode were verified live at L0–L3; Codex live at L0–L2 (M2: pre-edit denials reached the model's
  transcript; its stop gate is not declared yet); Cursor and Gemini CLI are documented-only
  (fixture-tested translators; no logged-in harness was available).
- "Declared" is the \`capabilities.level\` the adapter sent in its session hello. A declaration above the
  verified level is non-conformant (spec §3.3); below it is allowed (Codex declares L2 until its stop
  gate is re-probed live).
`;
writeFileSync(join(out, "README.md"), readme);
process.stderr.write(`\nwrote ${out}/README.md\n`);
