#!/usr/bin/env node
// Aggregate demo/evidence/m2/run-*/run.json into demo/evidence/m2-report.md.
//   node demo/m2-report.mjs [--write]
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = join(ROOT, "demo/evidence/m2");
const runs = (existsSync(DIR) ? readdirSync(DIR) : [])
  .filter((d) => /^run-\d+$/.test(d) && existsSync(join(DIR, d, "run.json")))
  .sort((a, b) => Number(a.slice(4)) - Number(b.slice(4)))
  .map((d) => ({ dir: d, ...JSON.parse(readFileSync(join(DIR, d, "run.json"), "utf8")) }));

const CRIT = [
  ["agents_live", "18 live agents (6 tasks × 3: Claude Code, Codex, OpenCode)"],
  ["collision_squiggle_reroute", "collision → live squiggle → reroute (t1 × t2)"],
  ["structural_merge", "same file, adjacent functions: structural merge where git conflicts (t4 × t5)"],
  ["negotiation_both_land", "negotiation: overload proposed, accepted, both land (t3 × t1)"],
  ["comparison_and_human_approval", "candidate comparison (previews + screenshots + review) + human approval (t6)"],
  ["trunk_green", "trunk typechecks + tests green after all landings"],
  ["auto_revert", "planted bug → error spike → auto-revert → task reopened"],
];
const yes = (b) => (b ? "PASS" : "FAIL");
const MARKS = ["seeded", "agents_ready", "planners_joined", "t1_signature_accepted", "plans_done", "t2_t3_done", "t1_done", "all_agents_done", "evidence_done", "landed", "trunk_checked", "auto_revert_done"];

const lines = [];
const L = (s = "") => lines.push(s);
L("# M2 report: the full demo, end to end on deployed infrastructure");
L();
L("Generated by `node demo/m2-report.mjs --write` from `demo/evidence/m2/run-*/run.json`.");
L("Scenario: `demo/scenarios/full.md`. Launcher: `demo/run-full.sh --run N`.");
L();
L("## Beats per run");
L();
L(`| beat | ${runs.map((r) => r.dir).join(" | ")} |`);
L(`|---|${runs.map(() => "---").join("|")}|`);
for (const [k, label] of CRIT) L(`| ${label} | ${runs.map((r) => (r.criteria?.[k] ? yes(r.criteria[k].ok) : r.error ? "aborted" : "—")).join(" | ")} |`);
L(`| **all beats** | ${runs.map((r) => (r.pass ? "**PASS**" : r.error ? `aborted: ${String(r.error).slice(0, 80)}` : "**FAIL**")).join(" | ")} |`);
L();
L("## Timings (seconds from start)");
L();
L(`| phase | ${runs.map((r) => r.dir).join(" | ")} |`);
L(`|---|${runs.map(() => "---:").join("|")}|`);
for (const m of MARKS) L(`| ${m} | ${runs.map((r) => r.marks?.[m] ?? "—").join(" | ")} |`);
L(`| total | ${runs.map((r) => r.duration_s ?? "—").join(" | ")} |`);
L();
for (const r of runs) {
  L(`## ${r.dir} (${r.started_at ?? ""})`);
  L();
  const ag = r.agents ?? [];
  L(`Agents: ${ag.length}; pushed: ${ag.filter((a) => a.push?.ok).length}; not pushed: ${ag.filter((a) => !a.push?.ok).map((a) => `${a.agent} (${a.push?.reason ?? "no push"})`).join(", ") || "none"}.`);
  const hf = r.criteria?.agents_live?.detail?.harness_failures ?? [];
  if (hf.length) L(`Harness failures: ${hf.map((h) => `${h.agent}: ${h.turns.map((t) => `${t.name} exit ${t.code}${t.failure ? ` (${t.failure.slice(0, 120)})` : ""}`).join("; ")}`).join(" · ")}`);
  L();
  L("| task | winner | approved by | land | layer | land op |");
  L("|---|---|---|---|---|---|");
  for (const [k, s] of Object.entries(r.selections ?? {})) L(`| ${k} | ${s.winner_agent ?? "—"} | ${s.approved_by ?? (s.result === "landing" ? "auto (low risk, clean review)" : "—")} | ${s.land?.status ?? s.status ?? "—"}${s.land?.reason ? ` (${s.land.reason})` : ""} | ${s.land?.layer ?? "—"} | ${s.land?.op_id ? s.land.op_id.slice(0, 12) : "—"} |`);
  L();
  const c = r.criteria ?? {};
  if (c.collision_squiggle_reroute) L(`Collision: t1 signature #${c.collision_squiggle_reroute.detail.t1_signature_seq}; t2 ${c.collision_squiggle_reroute.detail.t2.map((x) => `${x.agent}: ${x.rejected_seq ? `denied #${x.rejected_seq} (cause #${x.caused_by}), deny in transcript ${x.deny_in_transcript}, ${x.accepted_edits_after} accepted edits after` : "no stale_assumption"}`).join("; ")}.`);
  if (c.negotiation_both_land) {
    const n = c.negotiation_both_land.detail;
    L(`Negotiation: ${(n.proposals ?? []).map((p) => `#${p.seq} ${p.from} → ${p.to}: ${p.answer ? `${p.answer.kind} #${p.answer.seq}` : "unanswered"}`).join("; ") || "no proposals"}; t1 winner ${n.t1_winner ?? "—"}; overload on trunk ${n.overload_on_trunk}.`);
  }
  if (c.structural_merge) L(`Structural merge: land layers t4/t5 = ${c.structural_merge.detail.layers.join(" / ")}.`);
  if (c.comparison_and_human_approval) L(`Comparison: t6 candidates with screenshots ${c.comparison_and_human_approval.detail.t6_with_screenshots.join(", ") || "none"}; approved ${c.comparison_and_human_approval.detail.approved ? `${c.comparison_and_human_approval.detail.approved.agent} (${c.comparison_and_human_approval.detail.approved.why})` : "—"}.`);
  if (r.trunk) L(`Trunk after landings: tsc exit ${r.trunk.tsc?.exit}, node --test exit ${r.trunk.test?.exit} (${(r.trunk.test?.summary ?? []).join(", ")}).`);
  if (r.auto_revert) L(`Auto-revert: exit ${r.auto_revert.exit}.`);
  L();
}
const md = lines.join("\n") + "\n";
if (process.argv.includes("--write")) writeFileSync(join(ROOT, "demo/evidence/m2-report.md"), md);
process.stdout.write(md);
