// Bundle the adapter CLI into one ESM file that hooks run with plain `node`. The shared WCP
// core (packages/adapters/claude-code/src) is bundled in; `typescript` stays external and is
// loaded lazily only by hooks that analyze code.
import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(dirname(fileURLToPath(import.meta.url)));
await build({
  entryPoints: { "weft-cursor": join(here, "src/cli.ts") },
  outdir: join(here, "dist"),
  outExtension: { ".js": ".mjs" },
  chunkNames: "chunks/[name]-[hash]",
  splitting: true,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  external: ["typescript"],
  banner: { js: "// @weft/adapter-cursor — generated by scripts/build.mjs; do not edit." },
  logLevel: "warning",
});
