// The OpenCode plugin `install` writes to `<checkout>/.opencode/plugin/weft.js`. It runs
// inside OpenCode (Bun) and forwards each relevant plugin hook to the Node adapter bundle
// over stdin/stdout JSON, so all WCP logic stays in the shared core. Generated with absolute
// paths (node + bundle), so it is machine-specific and excluded from git.

export function pluginSource(node: string, bundle: string, mark: string): string {
  return `// ${mark}: generated by weft-adapter-opencode install — do not edit (re-run install).
// Forwards OpenCode plugin hooks to the Weft WCP adapter (${bundle}).
import { spawn } from "node:child_process";

const NODE = ${JSON.stringify(node)};
const BUNDLE = ${JSON.stringify(bundle)};

function ask(msg) {
  return new Promise((resolve) => {
    let out = "";
    let child;
    try {
      child = spawn(NODE, [BUNDLE, "hook"], { stdio: ["pipe", "pipe", "ignore"] });
    } catch {
      return resolve({});
    }
    const timer = setTimeout(() => child.kill("SIGKILL"), 30000);
    child.stdout.on("data", (c) => (out += c));
    child.on("error", () => resolve({}));
    child.on("close", () => {
      clearTimeout(timer);
      try { resolve(JSON.parse(out || "{}")); } catch { resolve({}); }
    });
    child.stdin.end(JSON.stringify(msg));
  });
}

export const WeftPlugin = async ({ client, directory }) => {
  const started = new Map(); // sessionID -> { full, short, used }

  async function welcome(sessionID) {
    if (!started.has(sessionID)) {
      const a = await ask({ kind: "system", sessionID, directory });
      const full = a.system ?? "";
      started.set(sessionID, { full, short: full.split("\\n")[0] ?? "", used: false });
    }
    const w = started.get(sessionID);
    const text = w.used ? w.short : w.full;
    w.used = true;
    return text;
  }

  return {
    "experimental.chat.system.transform": async (input, output) => {
      if (!input?.sessionID) return;
      const text = await welcome(input.sessionID);
      if (text) output.system.push(text);
    },
    "tool.execute.before": async (input, output) => {
      const a = await ask({ kind: "before", sessionID: input.sessionID, callID: input.callID, tool: input.tool, args: output.args, directory });
      if (a.deny) throw new Error(a.deny);
    },
    "tool.execute.after": async (input, output) => {
      const a = await ask({ kind: "after", sessionID: input.sessionID, callID: input.callID, tool: input.tool, args: input.args, output: typeof output.output === "string" ? output.output.slice(0, 4000) : "", directory });
      if (a.append) output.output = (typeof output.output === "string" ? output.output : String(output.output ?? "")) + "\\n\\n" + a.append;
    },
    event: async ({ event }) => {
      if (event?.type === "session.idle" && event.properties?.sessionID) {
        const sessionID = event.properties.sessionID;
        const a = await ask({ kind: "idle", sessionID, directory });
        if (a.prompt) {
          await client.session.prompt({ path: { id: sessionID }, body: { parts: [{ type: "text", text: a.prompt }] } }).catch(() => {});
        }
      } else if (event?.type === "session.deleted" && event.properties?.info?.id) {
        await ask({ kind: "end", sessionID: event.properties.info.id, directory });
      }
    },
  };
};
`;
}
